### ISSUE TITLE
Error on running .py file from terminal

### ISSUE THREAD

**Issue by Aryal007** [stmorgan/pythonNNexample#1]
Hi Siraj. There's a error on running .py file from command line

> Traceback (most recent call last):
>   File "PythonNNExampleFromSirajology.py", line 103, in <module>
>     get_ipython().run_cell_magic(u'HTML', u'', u'<iframe width="560" height="315" src="https://www.youtube.com/embed/h3l4qz76JhQ" frameborder="0" allowfullscreen></iframe>')
> NameError: name 'get_ipython' is not defined

**Comment by stmorgan** [comment]
Aryal:  

That error is from a call in Jupyter to embed Siraj's YouTube video. You can delete that line if you are running the Python script directly. 

You may also get an error on the print statements depending on which version of Python you are running. You can get around this by using the form using parentheses: print(...).   

Note that this is not Siraj's GitHub account. I coded this from watching his video and he kindly linked it in his video description. 

Thanks for your feedback!

Regards,
-Scott

**Comment by stmorgan** [comment]
Aryal: 

I'm going to close this issue. Please let me know if you have any additional difficulties. 

-Scott
