### ISSUE TITLE
Not actually an XOR

### ISSUE THREAD

**Issue by InDieTasten** [stmorgan/pythonNNexample#4]
In https://github.com/stmorgan/pythonNNexample/blob/master/PythonNNExampleFromSirajology.py#L32-L47

Inputs and expected outputs are layed out and labelled as being the values corresponding to the behavior of an XOR.

XOR describes being "activated", when one and only one of the inputs is "active". The current values do not form an XOR, but rather multiple XORs, which are activated, when the amount of active inputs is even.

The test set should either be labelled differently, or the values should be changed.

**Comment by stmorgan** [comment]
As noted in the text, the third column in the X matrix is for accommodating the bias term and is not one of the inputs, which are in the first two columns. So, the output is high when only one of the inputs is high. 
Thanks for contributing!

**Comment by InDieTasten** [comment]
Oh, I'm sorry. Pardon me. I didn't see that. Great work btw! Keep it up :)

**Comment by stmorgan** [comment]
No problem, and thanks! 
BTW, I've merged your typo in the Readme. Thanks!
